-- HR.S_EMP definition

CREATE TABLE "HR"."S_EMP" 
   (	
	"EMPLOYEE_ID" NUMBER(6,0), 
	"FIRST_NAME" VARCHAR2(20), 
	"LAST_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(25) NOT NULL ENABLE, 
	"PHONE_NUMBER" NUMBER, 
	"HIRE_DATE" DATE NOT NULL ENABLE, 
	"JOB_ID" VARCHAR2(10) NOT NULL ENABLE, 
	"SALARY" NUMBER(8,2), 
	"COMMISSION_PCT" NUMBER(2,2), 
	"MANAGER_ID" NUMBER(6,0), 
	"DEPARTMENT_ID" NUMBER(4,0)
   );
